### ISSUE TITLE
can i use ^0.20.0 in docker-compose?

### ISSUE THREAD

**Issue by Boyceman** [manyuanrong/deno_mongo#151]
something like this
`await client.connect({ servers: [{ host: 'database', port: 27017 }] })`

but nothing happened, and backend service is hunging up.

'database' is my service in docker-compose.yml

docker-compose.yml
```yml
version: '3.7'
services:
  database:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - './mongodb:/data/db'
    networks:
      - be_network

  backend:
    build: .
    ports:
      - '8080:8080'
    links:
      - database
    networks:
      - be_network
    depends_on:
      - database

networks:
  be_network:
```
